#context.objects = [
#	{ factory = adapter
#		args = {
#			factory.name           = api.alsa.pcm.source
#			node.name              = "umc22-source"
#			node.description       = "UMC22 Source"
#			media.class            = "Audio/Source"
#			api.alsa.path          = "hw:CODEC"
#			api.alsa.headroom	   = 192
#			audio.format           = "S16LE"
#			audio.rate             = 48000
#			audio.channels         = 1
#			audio.position         = "MONO"
#		}
#	}
#	{ factory = adapter
#		args = {
#			factory.name           = api.alsa.pcm.sink
#			node.name              = "umc22-sink"
#			node.description       = "UMC22 Sink"
#			media.class            = "Audio/Sink"
#			api.alsa.path          = "hw:CODEC"
#			api.alsa.headroom      = 192
#			audio.format           = "S16LE"
#			audio.rate             = 48000
#			audio.channels         = 2
#			audio.position         = "FL,FR"
#		}
#	}
#]
