#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload
hc keyunbind --all

# main binds
Mod=Mod4
hc keybind $Mod-Alt-q spawn ~/.config/herbstluftwm/quit.sh
hc keybind $Mod-Alt-r reload
hc keybind $Mod-Control-w close_and_remove
hc keybind $Mod-Return spawn kitty
hc keybind $Mod-Shift-w spawn ~/.config/herbstluftwm/close.sh
hc keybind $Mod-w close_or_remove
hc keybind $Mod-q remove


# focusing clients
hc keybind $Mod-Down focus down
hc keybind $Mod-Left focus left
hc keybind $Mod-Right focus right
hc keybind $Mod-Up focus up
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Down shift down
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
hc keybind $Mod-Shift-t attr clients.focus.floating false
hc keybind $Mod-o split right 0.5
hc keybind $Mod-t split auto
hc keybind $Mod-u split bottom 0.5

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-Down resize down +$resizestep
hc keybind $Mod-Control-Left resize left +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep
hc keybind $Mod-Control-Up resize up +$resizestep
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep
hc keybind $Mod-space spawn dmenu_run -m DisplayPort-0

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible

# layouting
hc keybind $Mod-BackSpace cycle_monitor
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-Shift-space cycle_layout 1 horizontal vertical
hc keybind $Mod-Tab cycle_all +1
hc keybind $Mod-e mirror
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-p spawn flameshot gui
hc keybind $Mod-r rotate
hc keybind $Mod-s attr clients.focus.floating toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# tags
tag_names=({0..9})
tag_keys=({0..9} 0) 

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        # first check if the tag is locked to some monitor.
        # if so, first focus the monitor
        hc keybind "$Mod-$key" \
            chain , silent substitute M tags."$i".my_monitor \
                        focus_monitor M \
                  , use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

lock_tag_to_monitor() {
    herbstclient chain \
        , new_attr string tags.by-name."$1".my_monitor \
        , set_attr tags.by-name."$1".my_monitor "$2"
}

lock_tag_to_monitor 1 0
lock_tag_to_monitor 2 0
lock_tag_to_monitor 3 0
lock_tag_to_monitor 4 0
lock_tag_to_monitor 5 0
lock_tag_to_monitor 6 1
lock_tag_to_monitor 7 1
lock_tag_to_monitor 8 1
lock_tag_to_monitor 9 1
lock_tag_to_monitor 0 1

# theme
hc attr theme.background_color "#181825"
hc attr theme.floating.reset 1
hc attr theme.tiling.outer_width 1
hc attr theme.tiling.reset 1
hc attr theme.active.color "#6c7086"
hc attr theme.normal.color "#181825"

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done

# settings
hc set auto_detect_monitors true
hc set auto_detect_panels true
hc set focus_follows_mouse true
hc set focus_stealing_prevention true
hc set frame_bg_active_color "#6c7086"
hc set frame_bg_normal_color "#181825"
hc set frame_bg_transparent true
hc set frame_border_active_color "#6c7086"
hc set frame_border_normal_color "#181825"
hc set frame_border_width 3
hc set frame_gap 4
hc set frame_padding -2
hc set hide_covered_windows true
hc set mouse_recenter_gap 0
hc set raise_on_focus_temporarily false
hc set show_frame_decorations "focused_if_multiple"
hc set smart_frame_surroundings off
hc set smart_window_surroundings on
hc set window_border_width 3
hc set window_gap -2
hc set tree_style "-| |'--."
hc set tabbed_max false
hc set swap_monitors_to_get_tag false
hc pad 0 0 0 0 0

# rules
hc unrule -F
hc rule fixedsize floating=on
hc rule class="cs2" tag=3 floating=false fullscreen=true keys_inactive="Mod4[+]w|Mod4[+]s|Mod4[+]f" ewmhrequests=false ewmhnotify=false switchtag=true
hc rule title="HorizonMW" tag=3 floating=false fullscreen=true keys_inactive="Mod4[+]w|Mod4[+]s|Mod4[+]f" ewmhrequests=false ewmhnotify=false switchtag=true
hc rule class="iw4x" tag=3 floating=false fullscreen=true keys_inactive="Mod4[+]w|Mod4[+]s|Mod4[+]f" ewmhrequests=false ewmhnotify=false switchtag=true
hc rule floatplacement=center
hc rule focus=on
hc rule windowtype="_NET_WM_WINDOW_TYPE_DIALOG" focus=on
hc rule windowtype~"_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)" floating=on
hc rule windowtype~"_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)" manage=off
hc rule index=e
hc unlock

# layout
herbstclient set default_frame_layout horizontal
hc substitute ALGO settings.default_frame_layout \
    foreach T tags.by-name. \
    sprintf ATTR "%c.tiling.root.algorithm" T \
    set_attr ATTR ALGO

# run once
if hc silent new_attr bool my_not_first_autostart; then
	gentoo-pipewire-launcher &
	dunst &
	hsetroot -solid "#080808"

	easyeffects --gapplication-service &
fi

# monitors
herbstclient focus_monitor 1; herbstclient use 6
herbstclient focus_monitor 0; herbstclient use 1
herbstclient set_monitors 1920x1080+0+0 1440x2560-1440+0

xrandr --output DisplayPort-0 --preferred --primary --filter nearest --mode 1920x1080 --rate 390 --pos 0x0
xrandr --output DisplayPort-1 --right-of DisplayPort-0 --filter nearest --set TearFree on --mode 2560x1440 --rate 70 --rotate normal --pos 1440x0

# audio settings
pw-metadata -n settings 0 clock.max-quantum 441
pw-metadata -n settings 0 clock.min-quantum 49
pw-metadata -n settings 0 clock.quantum 49
pw-metadata -n settings 0 clock.rate 44100
pw-metadata -n settings 0 clock.force-rate 44100
pw-metadata -n settings 0 clock.allowed-rates '[ 44100 48000 ]'
xset m 0 0
xset s default
xset dpms off
xset led off
xset b off

feh --bg-scale --randomize ~/Wallpapers/gentoo*png &
